// Generated by CoffeeScript 1.3.3
var App, getTweets;

getTweets = function(query) {
  return $.Deferred(function(defer) {
    return $.ajax({
      url: 'http://search.twitter.com/search.json',
      dataType: 'jsonp',
      data: {
        result_type: 'recent',
        rpp: 10,
        page: 1,
        q: query
      }
    }).done(function(res) {
      return defer.resolve(res.results);
    });
  }).promise();
};

App = Em.Application.create();

App.SearchButtonView = Em.View.extend({
  searchJQuery: function() {
    return App.tweets.update("jQuery");
  },
  searchEmber: function() {
    return App.tweets.update("Ember.js");
  }
});

App.tweets = Em.ArrayController.create({
  content: [],
  update: function(query) {
    var _this;
    _this = this;
    _this.set('content', []);
    return getTweets(query).done(function(tweets) {
      return _this.set('content', tweets);
    });
  }
});
